/*
*  RM2PT Generator Runtime
 * generated by RM2PT v1.3.0
 */
package com.rm2pt.generator.rm2doc

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
		
/**
 * Use this class to register components to be used within the Eclipse IDE.
 */ 
@FinalFieldsConstructor
class REMODELUiModule extends AbstractREMODELUiModule {
}

